global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

scrape_configs:
  - job_name: "machine metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://radarr:7878
        - http://sonarr:8989
        - http://ombi:3579
        - http://nzbget:6789
        - http://transmission:9091
        - http://jackett:9117
        - http://tautulli:8181
        - http://pihole:80
        - http://netdata:19999
        - http://portainer:9000
        - http://bitwarden:80
        - http://jupyterhub:8000
        - http://grafana:3000
        - http://duplicacy:3875
        - http://gsuite-backup:80
        - http://blackbox-exporter:9115
        - http://cadvisor:8080
        - http://prometheus:9090
        - http://nodeexporter:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
