{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Media Disk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/home\"} - node_filesystem_free_bytes{mountpoint=\"/home\"} )/ node_filesystem_size_bytes{mountpoint=\"/home\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Used Disk Space Media",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/home\", fstype=\"ext4\", device=\"/dev/md0\"} - node_filesystem_free_bytes{mountpoint=\"/home\", fstype=\"ext4\", device=\"/dev/md0\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PiHole",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://pihole:80\"}"
    }
   ]
  },
  {
   "title": "Jackett",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://jackett:9117\"}"
    }
   ]
  },
  {
   "title": "Netdata",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://netdata:19999\"}"
    }
   ]
  },
  {
   "title": "Sonarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://sonarr:8989\"}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tautulli",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://tautulli:8181\"}"
    }
   ]
  },
  {
   "title": "JupyterHub",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://jupyterhub:8000\"}"
    }
   ]
  },
  {
   "title": "NZBGet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://nzbget:6789\"}"
    }
   ]
  },
  {
   "title": "Duplicacy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://duplicacy:3875\"}"
    }
   ]
  },
  {
   "title": "Ombi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://ombi:3579\"}"
    }
   ]
  },
  {
   "title": "Portainer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://portainer:9000\"}"
    }
   ]
  },
  {
   "title": "Radarr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://radarr:7878\"}"
    }
   ]
  },
  {
   "title": "Transmission",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://transmission:9091\"}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bitwarden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://bitwarden:80\"}"
    }
   ]
  },
  {
   "title": "G Suite Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://gsuite-backup:80\"}"
    }
   ]
  },
  {
   "title": "Blackbox Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://blackbox-exporter:9115\"}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://nodeexporter:9100\"}"
    }
   ]
  },
  {
   "title": "CAdvisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://cadvisor:8080\"}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://prometheus:9090\"}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}